name: E2E Spark Integration Test

on:
  pull_request:

jobs:
  k8s-integration-tests:
    name: Run K8S integration tests with volcano
    runs-on: self-hosted
    env:
      SPARK_LOCAL_IP: localhost
    steps:
    - name: Checkout Spark repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: apache/spark
        ref: master
        path: ${{ github.workspace }}/spark-master
    - name: Checkout Volcano repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: volcano-sh/volcano
        ref: master
    - name: Install Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: start minikube
      run: |
        # Use pre-install minikube
        minikube start
    - name: Run K8S integration test
      run: |
        eval $(minikube docker-env)
        kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --group=system:serviceaccounts || true
        build/sbt -Pvolcano -Pkubernetes -Pkubernetes-integration-tests -Dtest.exclude.tags=minikube,r,local -Dtest.include.tags=volcano "kubernetes-integration-tests/test"
      working-directory: ${{ github.workspace }}/../../${{ github.repository }}/spark-master
    - name: Cleanup minikube
      run: |
        minikube delete
